name: Update Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "test"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic Metrics
        uses: lowlighter/metrics@v3.19
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes

